services:
  - type: web
    name: ai-calendar-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FREE_QUESTIONS_LIMIT
        value: 50
      - key: PREMIUM_QUESTIONS_LIMIT
        value: 100
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 200
      - key: LOG_LEVEL
        value: info
      - key: ALLOWED_ORIGINS
        value: chrome-extension://*,moz-extension://*,http://localhost:3000,http://localhost:5173

databases:
  - name: ai-calendar-db
    databaseName: ai_calendar_db
    user: ai_calendar_user
    plan: starter
